name : Python CI

on: 
  workflow_dispatch:
  push:
    branches:
      - main

jobs:
  tests:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
        name: Checkout my project
      - name: Install Python 3.10
        uses: actions/setup-python@v4
        with : 
          python-versions: "3.10"
      - name: Install requierements
        run: 
          python -m pip install -r requirements.txt 
      - name: Analysing the code with pylint
        run: |
          pylint --fail-under=8  $(git ls-files '*.py')
          pytest $(git ls-files '*.py')

